/* ============================================================
   Yayika — Share & Earn Schema
   Trackable achievement cards for social sharing
   ============================================================ */

-- ============================================================
-- TABLES
-- ============================================================

-- Share cards generated by users
CREATE TABLE IF NOT EXISTS yayika_share_cards (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  card_type TEXT NOT NULL, -- 'achievement', 'badge', 'streak', 'milestone', 'referral', 'custom'
  card_title JSONB NOT NULL, -- {"es":"Logro desbloqueado","en":"Achievement Unlocked",...}
  card_subtitle JSONB NOT NULL, -- {"es":"7 días de racha","en":"7-day streak",...}
  card_icon TEXT DEFAULT '🌟', -- Emoji or icon identifier
  card_color TEXT DEFAULT '#7B5EA7', -- Accent color
  card_data JSONB DEFAULT '{}', -- Extra data (badge_key, streak_count, etc.)
  ref_code TEXT, -- Embedded referral code
  share_url TEXT, -- Generated share URL
  share_count INT DEFAULT 0,
  view_count INT DEFAULT 0,
  click_count INT DEFAULT 0,
  conversion_count INT DEFAULT 0,
  platform TEXT, -- 'instagram', 'tiktok', 'whatsapp', 'twitter', 'copy', null
  is_public BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Track individual share events
CREATE TABLE IF NOT EXISTS yayika_share_events (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  card_id UUID REFERENCES yayika_share_cards(id) ON DELETE CASCADE NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  event_type TEXT NOT NULL, -- 'share', 'view', 'click', 'conversion'
  platform TEXT, -- 'instagram', 'tiktok', 'whatsapp', etc.
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Predefined card templates
CREATE TABLE IF NOT EXISTS yayika_share_templates (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  template_key TEXT UNIQUE NOT NULL,
  card_type TEXT NOT NULL,
  title JSONB NOT NULL,
  subtitle_template TEXT, -- Template with placeholders like {count}, {name}
  icon TEXT,
  color TEXT,
  gradient TEXT,
  is_active BOOLEAN DEFAULT true,
  sort_order INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- User share stats (aggregated)
CREATE TABLE IF NOT EXISTS yayika_share_stats (
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  total_shares INT DEFAULT 0,
  total_views INT DEFAULT 0,
  total_clicks INT DEFAULT 0,
  total_conversions INT DEFAULT 0,
  referral_signups INT DEFAULT 0,
  last_share_at TIMESTAMPTZ,
  share_streak INT DEFAULT 0,
  best_share_streak INT DEFAULT 0,
  xp_earned INT DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_sc_user ON yayika_share_cards(user_id);
CREATE INDEX IF NOT EXISTS idx_sc_type ON yayika_share_cards(card_type);
CREATE INDEX IF NOT EXISTS idx_sc_created ON yayika_share_cards(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_se_card ON yayika_share_events(card_id);
CREATE INDEX IF NOT EXISTS idx_se_user ON yayika_share_events(user_id);

-- ============================================================
-- SEED: Share card templates
-- ============================================================

INSERT INTO yayika_share_templates (template_key, card_type, title, subtitle_template, icon, color, gradient, sort_order) VALUES
('first_checkin_share', 'achievement', '{"es":"Mi primer check-in","en":"My first check-in","pt":"Meu primeiro check-in","fr":"Mon premier check-in","de":"Mein erstes Check-in"}', '{"es":"Empecé mi camino en Yayika","en":"I started my journey on Yayika","pt":"Comecei minha jornada no Yayika","fr":"J\'ai commencé mon parcours sur Yayika","de":"Ich habe meine Reise bei Yayika begonnen"}', '🌟', '#B8943A', 'linear-gradient(135deg, #B8943A 0%, #D4AF37 50%, #F0D060 100%)', 1),
('streak_7_share', 'streak', '{"es":"7 días de racha","en":"7-day streak","pt":"Sequência de 7 dias","fr":"Série de 7 jours","de":"7-Tage-Serie"}', '{"es":"{count} días seguidos cuidándome","en":"{count} days straight of self-care","pt":"{count} dias seguidos cuidando de mim","fr":"{count} jours d\'affilée à prendre soin de moi","de":"{count} Tage in Folge Selbstfürsorge"}', '🔥', '#C96B7A', 'linear-gradient(135deg, #C96B7A 0%, #E88A9E 50%, #FFB5C2 100%)', 2),
('streak_30_share', 'streak', '{"es":"30 días de racha","en":"30-day streak","pt":"Sequência de 30 dias","fr":"Série de 30 jours","de":"30-Tage-Serie"}', '{"es":"{count} días — ¡Una leyenda!","en":"{count} days — A legend!","pt":"{count} dias — Uma lenda!","fr":"{count} jours — Une légende !","de":"{count} Tage — Eine Legende!"}', '💎', '#7B5EA7', 'linear-gradient(135deg, #7B5EA7 0%, #A78BDB 50%, #D4B8F5 100%)', 3),
('badge_earned_share', 'badge', '{"es":"Badge desbloqueado","en":"Badge unlocked","pt":"Badge desbloqueado","fr":"Badge débloqué","de":"Badge freigeschaltet"}', '{"es":"{name} — {desc}","en":"{name} — {desc}","pt":"{name} — {desc}","fr":"{name} — {desc}","de":"{name} — {desc}"}', '🏆', '#5ED4A0', 'linear-gradient(135deg, #1A9E8F 0%, #5ED4A0 50%, #A8F0D4 100%)', 4),
('referral_share', 'referral', '{"es":"Invita a una amiga","en":"Invite a friend","pt":"Convide uma amiga","fr":"Invitez une amie","de":"Lade eine Freundin ein"}', '{"es":"{count} amigas ya se unieron","en":"{count} friends have joined","pt":"{count} amigas já se juntaram","fr":"{count} amies ont rejoint","de":"{count} Freundinnen sind schon beigetreten"}', '🌱', '#1A9E8F', 'linear-gradient(135deg, #1A9E8F 0%, #3BAF7A 50%, #5ED4A0 100%)', 5),
('cycle_master_share', 'milestone', '{"es":"Maestra del ciclo","en":"Cycle Master","pt":"Mestra do ciclo","fr":"Maîtresse du cycle","de":"Zyklusmeisterin"}', '{"es":"{count} ciclos registrados","en":"{count} cycles tracked","pt":"{count} ciclos registrados","fr":"{count} cycles suivis","de":"{count} Zyklen erfasst"}', '🌙', '#E8A0B0', 'linear-gradient(135deg, #E8A0B0 0%, #F0C5D0 50%, #FFDDE5 100%)', 6),
('community_share', 'achievement', '{"es":"Mi primer post","en":"My first post","pt":"Meu primeiro post","fr":"Mon premier post","de":"Mein erster Post"}', '{"es":"Me uní a la comunidad Yayika","en":"I joined the Yayika community","pt":"Juntei-me à comunidade Yayika","fr":"J\'ai rejoint la communauté Yayika","de":"Ich bin der Yayika-Community beigetreten"}', '💜', '#C96B7A', 'linear-gradient(135deg, #C96B7A 0%, #7B5EA7 50%, #5ED4C5 100%)', 7),
('earnings_share', 'milestone', '{"es":"Primera comisión","en":"First commission","pt":"Primeira comissão","fr":"Première commission","de":"Erste Provision"}', '{"es":"¡Ya gané dinero con Yayika!","en":"I earned money with Yayika!","pt":"Ganhei dinheiro com o Yayika!","fr":"J\'ai gagné de l\'argent avec Yayika!","de":"Ich habe mit Yayika Geld verdient!"}', '💰', '#B8943A', 'linear-gradient(135deg, #B8943A 0%, #5ED4A0 50%, #1A9E8F 100%)', 8)
ON CONFLICT (template_key) DO NOTHING;

-- ============================================================
-- FUNCTIONS
-- ============================================================

-- Create a share card
CREATE OR REPLACE FUNCTION yayika_create_share_card(
  p_user_id UUID,
  p_card_type TEXT,
  p_card_title JSONB,
  p_card_subtitle JSONB,
  p_card_icon TEXT DEFAULT '🌟',
  p_card_color TEXT DEFAULT '#7B5EA7',
  p_card_data JSONB DEFAULT '{}',
  p_ref_code TEXT DEFAULT NULL
) RETURNS UUID AS $$
DECLARE
  v_card_id UUID;
  v_share_url TEXT;
BEGIN
  -- Generate share URL with referral code
  v_share_url := 'https://yayika.com/share/' || p_ref_code || '?card=' || p_card_type;

  INSERT INTO yayika_share_cards (
    user_id, card_type, card_title, card_subtitle, card_icon, card_color,
    card_data, ref_code, share_url
  ) VALUES (
    p_user_id, p_card_type, p_card_title, p_card_subtitle, p_card_icon, p_card_color,
    p_card_data, p_ref_code, v_share_url
  ) RETURNING id INTO v_card_id;

  -- Update share stats
  INSERT INTO yayika_share_stats (user_id, total_shares, last_share_at, updated_at)
  VALUES (p_user_id, 1, NOW(), NOW())
  ON CONFLICT (user_id) DO UPDATE SET
    total_shares = yayika_share_stats.total_shares + 1,
    last_share_at = NOW(),
    updated_at = NOW();

  -- Record growth activity
  PERFORM yayika_record_growth_activity(p_user_id, 'share_click', jsonb_build_object('card_type', p_card_type, 'card_id', v_card_id));

  RETURN v_card_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Record a share event (platform share)
CREATE OR REPLACE FUNCTION yayika_record_share_event(
  p_card_id UUID,
  p_user_id UUID,
  p_event_type TEXT,
  p_platform TEXT DEFAULT NULL
) RETURNS VOID AS $$
BEGIN
  INSERT INTO yayika_share_events (card_id, user_id, event_type, platform)
  VALUES (p_card_id, p_user_id, p_event_type, p_platform);

  -- Update card counts
  IF p_event_type = 'share' THEN
    UPDATE yayika_share_cards SET share_count = share_count + 1, platform = p_platform WHERE id = p_card_id;
  ELSIF p_event_type = 'view' THEN
    UPDATE yayika_share_cards SET view_count = view_count + 1 WHERE id = p_card_id;
  ELSIF p_event_type = 'click' THEN
    UPDATE yayika_share_cards SET click_count = click_count + 1 WHERE id = p_card_id;
  ELSIF p_event_type = 'conversion' THEN
    UPDATE yayika_share_cards SET conversion_count = conversion_count + 1 WHERE id = p_card_id;
  END IF;

  -- Update user stats
  UPDATE yayika_share_stats SET
    total_views = total_views + CASE WHEN p_event_type = 'view' THEN 1 ELSE 0 END,
    total_clicks = total_clicks + CASE WHEN p_event_type = 'click' THEN 1 ELSE 0 END,
    total_conversions = total_conversions + CASE WHEN p_event_type = 'conversion' THEN 1 ELSE 0 END,
    referral_signups = referral_signups + CASE WHEN p_event_type = 'conversion' THEN 1 ELSE 0 END,
    updated_at = NOW()
  WHERE user_id = p_user_id;

  -- Award XP for sharing
  IF p_event_type = 'share' THEN
    UPDATE yayika_share_stats SET xp_earned = xp_earned + 10 WHERE user_id = p_user_id;
    PERFORM yayika_record_growth_activity(p_user_id, 'share_click', jsonb_build_object('platform', p_platform));
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Get user share stats
CREATE OR REPLACE FUNCTION yayika_get_share_stats(p_user_id UUID)
RETURNS TABLE(
  total_shares INT,
  total_views INT,
  total_clicks INT,
  total_conversions INT,
  referral_signups INT,
  share_streak INT,
  best_share_streak INT,
  xp_earned INT,
  recent_cards JSONB
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    COALESCE(ss.total_shares, 0),
    COALESCE(ss.total_views, 0),
    COALESCE(ss.total_clicks, 0),
    COALESCE(ss.total_conversions, 0),
    COALESCE(ss.referral_signups, 0),
    COALESCE(ss.share_streak, 0),
    COALESCE(ss.best_share_streak, 0),
    COALESCE(ss.xp_earned, 0),
    COALESCE((
      SELECT jsonb_agg(jsonb_build_object(
        'id', sc.id,
        'card_type', sc.card_type,
        'card_title', sc.card_title,
        'card_subtitle', sc.card_subtitle,
        'card_icon', sc.card_icon,
        'card_color', sc.card_color,
        'share_count', sc.share_count,
        'view_count', sc.view_count,
        'created_at', sc.created_at
      ) ORDER BY sc.created_at DESC)
      FROM yayika_share_cards sc WHERE sc.user_id = p_user_id LIMIT 10
    ), '[]'::jsonb)
  FROM yayika_share_stats ss
  WHERE ss.user_id = p_user_id;

  -- If no stats row, return empty
  IF NOT FOUND THEN
    total_shares := 0; total_views := 0; total_clicks := 0; total_conversions := 0;
    referral_signups := 0; share_streak := 0; best_share_streak := 0; xp_earned := 0;
    recent_cards := '[]'::jsonb;
    RETURN NEXT;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Get shareable card data for templates
CREATE OR REPLACE FUNCTION yayika_get_share_templates()
RETURNS TABLE(
  template_key TEXT,
  card_type TEXT,
  title JSONB,
  subtitle_template TEXT,
  icon TEXT,
  color TEXT,
  gradient TEXT
) AS $$
BEGIN
  RETURN QUERY
  SELECT st.template_key, st.card_type, st.title, st.subtitle_template, st.icon, st.color, st.gradient
  FROM yayika_share_templates st WHERE st.is_active = true ORDER BY st.sort_order;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE yayika_share_cards ENABLE ROW LEVEL SECURITY;
ALTER TABLE yayika_share_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE yayika_share_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE yayika_share_stats ENABLE ROW LEVEL SECURITY;

-- Public read: templates
CREATE POLICY "pub_read_templates" ON yayika_share_templates FOR SELECT USING (is_active = true);

-- Public read: public cards (for share links)
CREATE POLICY "pub_read_public_cards" ON yayika_share_cards FOR SELECT USING (is_public = true);

-- User: own cards
CREATE POLICY "user_read_own_cards" ON yayika_share_cards FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "user_insert_own_cards" ON yayika_share_cards FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "user_update_own_cards" ON yayika_share_cards FOR UPDATE USING (auth.uid() = user_id);

-- User: own events
CREATE POLICY "user_read_own_events" ON yayika_share_events FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "user_insert_own_events" ON yayika_share_events FOR INSERT WITH CHECK (auth.uid() = user_id);

-- User: own stats
CREATE POLICY "user_read_own_stats" ON yayika_share_stats FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "user_insert_own_stats" ON yayika_share_stats FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "user_update_own_stats" ON yayika_share_stats FOR UPDATE USING (auth.uid() = user_id);

-- Service role: full access
CREATE POLICY "svc_all_cards" ON yayika_share_cards FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "svc_all_events" ON yayika_share_events FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "svc_all_templates" ON yayika_share_templates FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "svc_all_stats" ON yayika_share_stats FOR ALL USING (auth.role() = 'service_role');
